version: 2
updates:
  - package-ecosystem: "npm" # Also works for Yarn.
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
